# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout creater
      run: |
        git clone https://github.com/BooruTagTranslation/Creater.git

    - name: Build tags
      run: |
        ls -la
        cd Creater
        sudo chmod +x gradlew
        ./gradlew run

    - name: Deploy to gh-pages
      run: |
        cd Creater
        cd gradle
        git config --global user.email "server@yojigen.tech"
        git config --global user.name "ServerChan"
        git init
        git add .
        git commit -m "Server commit"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/BooruTagTranslation/Database.git" master:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
